# Указание Gradle Wrapper
GRADLE = ./gradlew

# Основные цели
.PHONY: all build clean run

# запуск дистрибутива
run-dist:
	./build/install/app/bin/app

# Сборка проекта
build:
	$(GRADLE) build

# Очистка проекта
clean:
	$(GRADLE) clean

# Запуск проекта
run:
	$(GRADLE) run
